theme: jekyll-theme-cayman
title: typingEffect.js (Github)
show_downloads: true
github.zip_url: http://lnps.co.uk/customLibraries/customWriting/typingEffect.js
github.another_url: http://lnps.co.uk/customLibraries/customWriting/demo.html
